openapi: 3.0.0
info:
  title: App Connection API
  version: '1.0'
servers:
  - url: 'https://octoeverywhere.com'
paths:
  /api/appconnection/info:
    parameters: []
    get:
      summary: App Connection OctoEverywhere API
      tags: []
      responses:
        '200':
          description: The App Connection is valid and the current information has been returned.
          content:
            application/json:
              schema:
                type: object
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '400':
          description: The App Token was missing from the body or header.
        '402':
          description: 'The owner''s account is no longer a supporter. If the account is upgraded to supporter status again, this connection will become valid once again.'
        '404':
          description: The App Token is invlaid and no App Connection could be found to match it.
        '410':
          description: The App Connection has been revoked by the user and will never be valid again.
      operationId: get-users-userId
      description: |-
        To get information about an App Connection, you must set the `AppToken` header with the API Token returned from the App Connection Portal.

        To figure out the App Connection and printer's state, you can use a combination of the API return type as well as the `IsOnline` flag in the resposne body. 
      parameters:
        - schema:
            type: string
          in: header
          name: AppToken
          description: The App Connection API Token
          required: true
components:
  schemas: {}
